export const types = {
    MOVIES_LOADED: 'MOVIES_LOADED',
    START_LOADING: 'START_LOADING',
    MOVIE_REMOVED: 'MOVIE_REMOVED',
    TOGGLE_MODAL: 'TOGGLE_MODAL',
    SET_CURRENT_MOVIE: 'SET_CURRENT_MOVIE'
}